onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - unrs-resolver

# https://pnpm.io/settings#shellemulator
shellEmulator: true

# https://pnpm.io/settings#strictdepbuilds
strictDepBuilds: true
